### ISSUE TITLE
输入维度相关

### ISSUE THREAD

**Issue by LitschiYan** [Feaxure-fresh/TL-Bearing-Fault-Diagnosis#10]
您好，首先非常感谢您提供的迁移学习代码；
我想请问一下如果我想要将输入形式从“.mat‘’改为二维图片，需要修改哪些地方呢，我刚开始学习故障诊断方向，如果您能回复我将感激不尽！

**Comment by Feaxure-fresh** [comment]
如果您确切地知道自己想要做什么，并且打算调整该资源库的代码以适用 2D 数据，那么这将是一项需要仔细考虑的任务。您可以采取以下方法：

1. 修改数据加载和数据集构建脚本（文件 data_loader/data_utils.py，以及 data_loader/load.py 或 data_loader/conditional_load.py）。模型原本接受格式为 (batch_size, 1, sequence_length) 的数据，您可能需要将其 reshape 为（batch_size, channels, height, width）。 直接将时间序列数据从一维 reshape 为二维可能并不合理，通常需要采用更合适的方法来进行这种转换。

2. 调整数据增强（考虑对 data_loader/aug.py 进行必要的更改以适应您的新数据格式）。 这可能涉及修改数据增强函数处理 2D 数据的方式。

3. 更新模型架构（文件 models/model_base.py 以及您计划使用的任何特定方法）。 现有的模型架构使用 Conv1d、BatchNorm1d 和 MaxPool1d 层。 对于 2D 数据，您必须将它们切换为对应的 2D 层。 并且，这涉及根据您的需要调整每层的 in_channels 和 out_channels 。

**Comment by LitschiYan** [comment]
非常非常感谢您耐心的回复！我会将您的回复认真学习，祝您生活顺利，健康平安！
