### ISSUE TITLE
The detail of using openset mode

### ISSUE THREAD

**Issue by AI-Explorer-Lab** [Feaxure-fresh/TL-Bearing-Fault-Diagnosis#19]
Hi I found that many method used in closed-set can be used in open-set, and I want to learn from it. So can you tell me how to find the detail code of achieving open-set in your repository? Thank you!

**Comment by Wenbo-Qin** [comment]
Hi, I have found that "When models originally designed for closed-set are used in open-set or universal scenarios, the Closed-set-acc (which excludes categories present in the target domain but absent in the source domain) will also be reported." But I wonder how to distinguish that whether the model can be used in Openset scenario ^_^

**Comment by Feaxure-fresh** [comment]
The open-set mode is only useful for methods with open-set classification ability. Many closed-set methods can be used in open-set mode for comparison purposes, but they will classify all unknown classes into existing categories, resulting in 0% accuracy for those unknown classes. Additionally, Closed-set accuracy (which excludes categories present in the target domain but not the source domain) will also be reported for reference.
