### ISSUE TITLE
 `PU_op.data_preprare()` and `XJTU_op.data_preprare()` 

### ISSUE THREAD

**Issue by ningjiaen123** [Feaxure-fresh/TL-Bearing-Fault-Diagnosis#3]
The functions `PU_op.data_preprare()` and `XJTU_op.data_preprare()` do not have the `source_label` parameter. However, in the `_init_data` function, when calling `data_preprare`, a `source_label` parameter is passed every time, as shown below:
```
self.datasets[source] = Dataset(data_root, args.normlizetype, random_state=args.random_state,
                                op=op).data_preprare(source_label=idx, is_src=True)
```

**Comment by Feaxure-fresh** [comment]
Thanks for pointing out the mistake. Clearly this is an incompatibility issue in the code. A correction has been made.
